export const EXAMPLE = [
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'PRIMARY',
    candidate_office: null,
    amendment_indicator_desc: 'ADD',
    contribution_receipt_date: '2015-03-28T00:00:00',
    conduit_committee_zip: null,
    memo_text: null,
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: null,
    file_number: 1002365,
    contributor_name: 'TOUPS, JOHN M',
    report_type: 'Q1',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15',
    back_reference_transaction_id: null,
    line_number: '11AI',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: '2016',
    candidate_office_district: null,
    contributor_aggregate_ytd: 2700,
    conduit_committee_name: null,
    contributor_middle_name: 'M',
    link_id: 4041320151241788000,
    conduit_committee_street1: null,
    sub_id: '4041420151241806268',
    contribution_receipt_amount: 2700,
    candidate_office_full: null,
    line_number_label: 'Contributions From Individuals/Persons Other Than Political Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: 'CONTRIBUTION',
    memoed_subtotal: false,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?15951125925',
    amendment_indicator: 'A',
    candidate_suffix: null,
    report_year: 2015,
    filing_form: 'F3',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'VNJ1EDNE0T3',
    committee_id: 'C00555888',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'P2016',
    back_reference_schedule_name: null,
    image_number: '15951125925',
    committee: {
      designation: 'P',
      state_full: 'Virginia',
      zip: '22314',
      designation_full: 'Principal campaign committee',
      party: 'DEM',
      committee_type: 'H',
      committee_type_full: 'House',
      cycle: 2016,
      party_full: 'DEMOCRATIC PARTY',
      state: 'VA',
      candidate_ids: [
        'H4VA08224'
      ],
      treasurer_name: 'WHIPPLE, MARY MARGARET MS.',
      city: 'ALEXANDRIA',
      organization_type: null,
      committee_id: 'C00555888',
      cycles: [
        2018,
        2016,
        2014
      ],
      name: 'FRIENDS OF DON BEYER',
      street_2: null,
      organization_type_full: null,
      street_1: '1751 POTOMAC GREENS DRIVE'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'GENERAL',
    candidate_office: null,
    amendment_indicator_desc: 'ADD',
    contribution_receipt_date: '2015-03-31T00:00:00',
    conduit_committee_zip: null,
    memo_text: null,
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: null,
    file_number: 1002365,
    contributor_name: 'TOUPS, JOHN M',
    report_type: 'Q1',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15',
    back_reference_transaction_id: null,
    line_number: '11AI',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: '2016',
    candidate_office_district: null,
    contributor_aggregate_ytd: 5400,
    conduit_committee_name: null,
    contributor_middle_name: 'M',
    link_id: 4041320151241788000,
    conduit_committee_street1: null,
    sub_id: '4041420151241806255',
    contribution_receipt_amount: 2700,
    candidate_office_full: null,
    line_number_label: 'Contributions From Individuals/Persons Other Than Political Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: 'CONTRIBUTION',
    memoed_subtotal: false,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?15951125921',
    amendment_indicator: 'A',
    candidate_suffix: null,
    report_year: 2015,
    filing_form: 'F3',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'VNJ1EDNGKF2',
    committee_id: 'C00555888',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'G2016',
    back_reference_schedule_name: null,
    image_number: '15951125921',
    committee: {
      designation: 'P',
      state_full: 'Virginia',
      zip: '22314',
      designation_full: 'Principal campaign committee',
      party: 'DEM',
      committee_type: 'H',
      committee_type_full: 'House',
      cycle: 2016,
      party_full: 'DEMOCRATIC PARTY',
      state: 'VA',
      candidate_ids: [
        'H4VA08224'
      ],
      treasurer_name: 'WHIPPLE, MARY MARGARET MS.',
      city: 'ALEXANDRIA',
      organization_type: null,
      committee_id: 'C00555888',
      cycles: [
        2018,
        2016,
        2014
      ],
      name: 'FRIENDS OF DON BEYER',
      street_2: null,
      organization_type_full: null,
      street_1: '1751 POTOMAC GREENS DRIVE'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'PRIMARY',
    candidate_office: null,
    amendment_indicator_desc: 'ADD',
    contribution_receipt_date: '2015-11-02T00:00:00',
    conduit_committee_zip: null,
    memo_text: null,
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: null,
    file_number: 1042396,
    contributor_name: 'TOUPS, JOHN M',
    report_type: 'YE',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15',
    back_reference_transaction_id: null,
    line_number: '11AI',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: null,
    candidate_office_district: null,
    contributor_aggregate_ytd: 5000,
    conduit_committee_name: null,
    contributor_middle_name: 'M',
    link_id: 4012620161260874000,
    conduit_committee_street1: null,
    sub_id: '4012720161260932887',
    contribution_receipt_amount: 5000,
    candidate_office_full: null,
    line_number_label: 'Contributions From Individuals/Persons Other Than Political Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: 'CONTRIBUTION',
    memoed_subtotal: false,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201601269004610465',
    amendment_indicator: 'A',
    candidate_suffix: null,
    report_year: 2015,
    filing_form: 'F3X',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'VNJ1EE3Y4P7',
    committee_id: 'C00566562',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'P',
    back_reference_schedule_name: null,
    image_number: '201601269004610465',
    committee: {
      designation: 'B',
      state_full: 'Virginia',
      zip: '22314',
      designation_full: 'Lobbyist/Registrant PAC',
      party: null,
      committee_type: 'N',
      committee_type_full: 'PAC - Nonqualified',
      cycle: 2016,
      party_full: null,
      state: 'VA',
      candidate_ids: [ ],
      treasurer_name: 'BUCHANAN, KATHERINE M',
      city: 'ALEXANDRIA',
      organization_type: null,
      committee_id: 'C00566562',
      cycles: [
        2016,
        2018,
        2014
      ],
      name: 'BACKPAC',
      street_2: null,
      organization_type_full: null,
      street_1: '1751 POTOMAC GREENS DRIVE'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'PRIMARY',
    candidate_office: null,
    amendment_indicator_desc: 'NO CHANGE',
    contribution_receipt_date: '2016-08-13T00:00:00',
    conduit_committee_zip: null,
    memo_text: '* BENNETT VICTORY FUND',
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: 'X',
    file_number: 1162748,
    contributor_name: 'TOUPS, JOHN M.',
    report_type: 'M9',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15J',
    back_reference_transaction_id: null,
    line_number: '12',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: null,
    candidate_office_district: null,
    contributor_aggregate_ytd: 10000,
    conduit_committee_name: null,
    contributor_middle_name: 'M.',
    link_id: 4051720171404971000,
    conduit_committee_street1: null,
    sub_id: '4051720171405068635',
    contribution_receipt_amount: 10000,
    candidate_office_full: null,
    line_number_label: 'Transfers from Authorized Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
    memoed_subtotal: true,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201705179053924469',
    amendment_indicator: 'N',
    candidate_suffix: null,
    report_year: 2016,
    filing_form: 'F3X',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'VSGYHCRHWZ2',
    committee_id: 'C00155952',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'P',
    back_reference_schedule_name: null,
    image_number: '201705179053924469',
    committee: {
      designation: 'U',
      state_full: 'Virginia',
      zip: '23219',
      designation_full: 'Unauthorized',
      party: 'DEM',
      committee_type: 'Y',
      committee_type_full: 'Party - Qualified',
      cycle: 2016,
      party_full: 'DEMOCRATIC PARTY',
      state: 'VA',
      candidate_ids: [ ],
      treasurer_name: 'KLEAR, BARBARA',
      city: 'RICHMOND',
      organization_type: null,
      committee_id: 'C00155952',
      cycles: [
        2004,
        1986,
        2012,
        2018,
        1990,
        1996,
        2016,
        1998,
        2010,
        2006,
        1988,
        1982,
        2002,
        2000,
        1994,
        2014,
        1984,
        1992,
        2008
      ],
      name: 'DEMOCRATIC PARTY OF VIRGINIA',
      street_2: 'SUITE 2050',
      organization_type_full: null,
      street_1: '919 EAST MAIN STREET'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'GENERAL',
    candidate_office: null,
    amendment_indicator_desc: 'NO CHANGE',
    contribution_receipt_date: '2016-09-25T00:00:00',
    conduit_committee_zip: null,
    memo_text: '* HILLARY VICTORY FUND',
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: 'X',
    file_number: 1137625,
    contributor_name: 'TOUPS, JOHN',
    report_type: 'M10',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15J',
    back_reference_transaction_id: 'C10959134',
    line_number: '18',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: '2016',
    candidate_office_district: null,
    contributor_aggregate_ytd: 2700,
    conduit_committee_name: null,
    contributor_middle_name: null,
    link_id: 4010920171359608000,
    conduit_committee_street1: null,
    sub_id: '4011120171366310375',
    contribution_receipt_amount: 2700,
    candidate_office_full: null,
    line_number_label: 'Transfers From Other Authorized Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
    memoed_subtotal: true,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201701099041182048',
    amendment_indicator: 'N',
    candidate_suffix: null,
    report_year: 2016,
    filing_form: 'F3P',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'C12446525',
    committee_id: 'C00575795',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'G2016',
    back_reference_schedule_name: 'SA18',
    image_number: '201701099041182048',
    committee: {
      designation: 'P',
      state_full: 'New York',
      zip: '101855256',
      designation_full: 'Principal campaign committee',
      party: 'DEM',
      committee_type: 'P',
      committee_type_full: 'Presidential',
      cycle: 2016,
      party_full: 'DEMOCRATIC PARTY',
      state: 'NY',
      candidate_ids: [
        'P00003392'
      ],
      treasurer_name: 'VILLARREAL, JOSE H.',
      city: 'NEW YORK',
      organization_type: null,
      committee_id: 'C00575795',
      cycles: [
        2018,
        2016
      ],
      name: 'HILLARY FOR AMERICA',
      street_2: null,
      organization_type_full: null,
      street_1: 'P.O. BOX 5256'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'GENERAL',
    candidate_office: null,
    amendment_indicator_desc: 'NO CHANGE',
    contribution_receipt_date: '2016-09-25T00:00:00',
    conduit_committee_zip: null,
    memo_text: '* HILLARY VICTORY FUND',
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: 'X',
    file_number: 1164593,
    contributor_name: 'TOUPS, JOHN MELBURN',
    report_type: '30G',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15J',
    back_reference_transaction_id: 'C33176585',
    line_number: '12',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: '2016',
    candidate_office_district: null,
    contributor_aggregate_ytd: 22300,
    conduit_committee_name: null,
    contributor_middle_name: 'MELBURN',
    link_id: 4060120171405955600,
    conduit_committee_street1: null,
    sub_id: '4060220171406352009',
    contribution_receipt_amount: 22300,
    candidate_office_full: null,
    line_number_label: 'Transfers from Authorized Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
    memoed_subtotal: true,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201706019055200081',
    amendment_indicator: 'N',
    candidate_suffix: null,
    report_year: 2016,
    filing_form: 'F3X',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'C33280031',
    committee_id: 'C00010603',
    contributor_employer: 'RETIRED',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'G2016',
    back_reference_schedule_name: 'SA12',
    image_number: '201706019055200081',
    committee: {
      designation: 'U',
      state_full: 'District Of Columbia',
      zip: '20003',
      designation_full: 'Unauthorized',
      party: 'DEM',
      committee_type: 'Y',
      committee_type_full: 'Party - Qualified',
      cycle: 2016,
      party_full: 'DEMOCRATIC PARTY',
      state: 'DC',
      candidate_ids: [ ],
      treasurer_name: 'ANDREW TOBIAS',
      city: 'WASHINGTON',
      organization_type: null,
      committee_id: 'C00010603',
      cycles: [
        2004,
        1978,
        1988,
        2006,
        1996,
        2010,
        1994,
        2016,
        1982,
        2014,
        2000,
        1984,
        1998,
        1986,
        2002,
        2018,
        2012,
        1992,
        1990,
        1976,
        2008,
        1980
      ],
      name: "DNC SERVICES CORP./DEM. NAT'L COMMITTEE",
      street_2: null,
      organization_type_full: null,
      street_1: '430 SOUTH CAPITOL ST SE'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT APT 102',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'PRIMARY',
    candidate_office: null,
    amendment_indicator_desc: 'NO CHANGE',
    contribution_receipt_date: '2016-09-25T00:00:00',
    conduit_committee_zip: null,
    memo_text: null,
    candidate_first_name: null,
    load_date: '2017-11-08T04:47:02.757174+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: null,
    file_number: 1180866,
    contributor_name: 'TOUPS, JOHN',
    report_type: 'Q3',
    receipt_type_full: null,
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15',
    back_reference_transaction_id: null,
    line_number: '11AI',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: null,
    candidate_office_district: null,
    contributor_aggregate_ytd: 25000,
    conduit_committee_name: null,
    contributor_middle_name: null,
    link_id: 4083120171447880700,
    conduit_committee_street1: null,
    sub_id: '4090120171448313059',
    contribution_receipt_amount: 25000,
    candidate_office_full: null,
    line_number_label: 'Contributions From Individuals/Persons Other Than Political Committees',
    contributor_state: 'VA',
    timestamp: '2017-11-08T04:47:02.757174+00:00',
    receipt_type_desc: 'CONTRIBUTION',
    memoed_subtotal: false,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201708319071248276',
    amendment_indicator: 'N',
    candidate_suffix: null,
    report_year: 2016,
    filing_form: 'F3X',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'C11180205',
    committee_id: 'C00586537',
    contributor_employer: 'N/A',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '221015670',
    election_type_full: null,
    election_type: 'P',
    back_reference_schedule_name: null,
    image_number: '201708319071248276',
    committee: {
      designation: 'J',
      state_full: 'New York',
      zip: '101855256',
      designation_full: 'Joint fundraising committee',
      party: null,
      committee_type: 'N',
      committee_type_full: 'PAC - Nonqualified',
      cycle: 2016,
      party_full: null,
      state: 'NY',
      candidate_ids: [ ],
      treasurer_name: 'JONES, ELIZABETH',
      city: 'NEW YORK',
      organization_type: null,
      committee_id: 'C00586537',
      cycles: [
        2018,
        2016
      ],
      name: 'HILLARY VICTORY FUND',
      street_2: null,
      organization_type_full: null,
      street_1: 'PO BOX 5256'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'RETIRED',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  },
  {
    memo_code_full: null,
    conduit_committee_street2: null,
    candidate_middle_name: null,
    schedule_type: 'SA',
    cycle: 2016,
    conduit_committee_city: null,
    fec_election_type_desc: 'PRIMARY',
    candidate_office: null,
    amendment_indicator_desc: 'NO CHANGE',
    contribution_receipt_date: '2016-12-27T00:00:00',
    conduit_committee_zip: null,
    memo_text: null,
    candidate_first_name: null,
    load_date: '2018-01-13T09:00:12.153261+00:00',
    candidate_office_state_full: null,
    contributor_prefix: null,
    memo_code: null,
    file_number: 1197015,
    contributor_name: 'TOUPS, JOHN M',
    report_type: 'YE',
    receipt_type_full: 'INDIVIDUAL CONTRIBUTION',
    original_sub_id: null,
    contributor_first_name: 'JOHN',
    receipt_type: '15',
    back_reference_transaction_id: null,
    line_number: '11AI',
    conduit_committee_state: null,
    entity_type_desc: 'INDIVIDUAL',
    fec_election_year: null,
    candidate_office_district: null,
    contributor_aggregate_ytd: 1000,
    conduit_committee_name: null,
    contributor_middle_name: 'M',
    link_id: 4011220181502831600,
    conduit_committee_street1: null,
    sub_id: '4011220181502835078',
    contribution_receipt_amount: 1000,
    candidate_office_full: null,
    line_number_label: null,
    contributor_state: 'VA',
    timestamp: '2018-01-13T02:05:13.370001+00:00',
    receipt_type_desc: 'CONTRIBUTION',
    memoed_subtotal: false,
    pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?201801119090397506',
    amendment_indicator: 'N',
    candidate_suffix: null,
    report_year: 2016,
    filing_form: 'F3X',
    two_year_transaction_period: 2016,
    contributor_id: null,
    transaction_id: 'SA11AI.5169',
    committee_id: 'C00479980',
    contributor_employer: 'PLANNING RESEARCH CORP.',
    conduit_committee_id: null,
    contributor_city: 'MC LEAN',
    candidate_office_state: null,
    candidate_name: null,
    committee_name: null,
    contributor_street_2: 'APT 102',
    schedule_type_full: 'ITEMIZED RECEIPTS',
    contributor_last_name: 'TOUPS',
    contributor_zip: '22101',
    election_type_full: null,
    election_type: 'P',
    back_reference_schedule_name: null,
    image_number: '201801119090397506',
    committee: {
      designation: 'U',
      state_full: 'Virginia',
      zip: '22046',
      designation_full: 'Unauthorized',
      party: null,
      committee_type: 'N',
      committee_type_full: 'PAC - Nonqualified',
      cycle: 2016,
      party_full: null,
      state: 'VA',
      candidate_ids: [ ],
      treasurer_name: 'MAJ BRIAN A HAMPTON USAR (RET)',
      city: 'FALLS CHURCH',
      organization_type: null,
      committee_id: 'C00479980',
      cycles: [
        2018,
        2010,
        2014,
        2016,
        2012
      ],
      name: 'PUT VETS FIRST! PAC',
      street_2: null,
      organization_type_full: null,
      street_1: '210 E BROAD ST SUITE 202'
    },
    increased_limit: null,
    is_individual: true,
    candidate_last_name: null,
    donor_committee_name: null,
    candidate_id: null,
    contributor: null,
    contributor_street_1: '7222 FARM MEADOW CT',
    national_committee_nonfederal_account: null,
    unused_contbr_id: null,
    contributor_occupation: 'PRESIDENT/CEO',
    contributor_suffix: null,
    entity_type: 'IND',
    candidate_prefix: null
  }
]
